CREATE ROLE app LOGIN PASSWORD 'apppass';
ALTER ROLE app CONNECTION LIMIT 30;
ALTER ROLE app SET statement_timeout = '20s';

CREATE ROLE readonly LOGIN PASSWORD 'readonlypass';
ALTER ROLE readonly CONNECTION LIMIT 5;
ALTER ROLE readonly SET statement_timeout = '2min';

CREATE ROLE developer LOGIN PASSWORD 'devpass';
ALTER ROLE developer CONNECTION LIMIT 10;
ALTER ROLE developer SET statement_timeout = '5min';

GRANT CONNECT ON DATABASE course_db TO app, readonly, developer;
GRANT USAGE ON SCHEMA public TO app, readonly, developer;

GRANT USAGE, SELECT
    ON ALL SEQUENCES IN SCHEMA public TO app;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public TO app;

GRANT SELECT
    ON ALL TABLES IN SCHEMA public TO readonly;

GRANT ALL PRIVILEGES
    ON ALL TABLES IN SCHEMA public TO developer;

GRANT ALL PRIVILEGES
    ON ALL SEQUENCES IN SCHEMA public TO developer;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT ON TABLES TO readonly;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO developer;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO app, developer;
