services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=docker_cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    ports:
      - "9042:9042"  # CQL-порт (только для первой ноды)
    volumes:
      - cassandra1_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q '^UN'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    depends_on:
      cassandra1:
        condition: service_healthy
    environment:
      - CASSANDRA_CLUSTER_NAME=docker_cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra2_data:/var/lib/cassandra

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    depends_on:
      cassandra1:
        condition: service_healthy
    environment:
      - CASSANDRA_CLUSTER_NAME=docker_cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra3_data:/var/lib/cassandra

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data: